---
title: "Police Complaints Data"
author: "Ajay Malik"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Percentage Analysis

```{r, echo = FALSE}
raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv", 
              col_types = cols(complaint_id = col_character(),
                               date_received = col_date(format = ""),
                               district_occurrence = col_character(),
                               general_cap_classification = col_character(),
                               summary = col_character(),
                               officer_id = col_factor(),
                               po_race = col_character(),
                               po_sex = col_character(),
                               po_assigned_unit = col_character(),
                               allegations_investigated = col_character(),
                               investigative_findings = col_character(),
                               disciplinary_findings = col_character())) %>% 
  select(officer_id, po_race, po_sex)
```

```{r, echo = FALSE}
clean_data <- raw_data %>% 
  group_by(officer_id) %>%  
  summarize(total = n()) %>%
  mutate(compl_dec = ntile(total, 10)) %>%
  group_by(compl_dec) %>%
  summarize(compl_total = sum(total)) %>%
  mutate(percentage = compl_total/sum(compl_total))
```

```{r, echo = FALSE}
clean_data %>%
  ggplot(mapping = aes(x = compl_dec,
                       y = percentage,
                       fill = compl_total)) + 
    geom_col() + 
    scale_y_continuous(labels = scales::percent_format()) +
    theme_bw() + 
    scale_x_continuous() + 
    labs(title = "In Philadelphia, a small group of officers generate a disproportionate \n share of misconduct complaints",
         subtitle = "Distribution of civilian misconduct complaints, by decile",
         y = "Percentage of complaints",
         x = "Officers are ranked by number of complaints and grouped into deciles",
         fill = "Total complaints \n per decile",
         caption = "Source: OpenDataPhilly and Sam Learner (Philadelphia)")
```