---
title: "Officer Complaint Data for Philadelphia, Chicago, and New York"
author: "Ajay Malik"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)

raw_data_ph <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>% 
  select(officer_id)  

raw_data_ny <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/nyc_clean.csv") %>% 
  select(OfficerID) 

raw_data_ch <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/chicago_clean.csv") %>% 
  select(UID) 
```


```{r, cleaning}

data_ph <- raw_data_ph %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc)

data_ny <- raw_data_ny %>% 
 group_by(OfficerID) %>% 
  summarize(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) 
  
 data_ch <- raw_data_ch %>% 
  group_by(UID) %>% 
  summarize(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) 
```

```{r joining}
data_ph <- data_ph %>% 
  mutate(city = "Philadelphia")

data_ny <- data_ny %>% 
  mutate(city = "New York")
  
data_ch <- data_ch %>% 
  mutate(city = "Chicago")
  
clean_data <- bind_rows(data_ph, data_ny, data_ch) 
```

```{r, plotting}
fill_dec <- if_else(clean_data$compl_dec == 10, "#7FD4E6", "#00558F")

clean_data %>% 
  ggplot(aes(x = compl_dec, y = compl_perc)) +
  geom_col(fill = if_else(clean_data$compl_dec == 10, "#7FD4E6", "#00558F")) +
  labs(title = "In several US cities, a small group of officers generate a\ndisproportionate share of misconduct complaints",
         subtitle = "Distribution of civilian misconduct complaints, by decile",
         x = "Officers are ranked by number of complaints and grouped into deciles",
         y = NULL,
         caption = "Data for Chicago and New York are from 2007 to 2017 and include only closed complaints\nData for Philadelphia are from April 2015 to March 2021 and include pending complaints\nSources: Invisible Institute (Chicago); New York Civil Liberties Union (New York); OpenDataPhilly and\nSam Learner (Philadelphia)") +
  facet_wrap(~ city, nrow = 1) +
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_economist() +
  theme(plot.background = element_rect(fill = "#FFF0E3"))
```